1. This is printed by line 9: 
values added:  20
2. This is printed by line 13:
final result:  20
3. This is printed by line 9:
   values added:  20
4. The code returns an error because the result variable was defined with "let" inside of the if statement. The console.log uses "result" on line 13 outside of the scope and thus it does not recognize the variable.
5. The code returns an error because in line 7, you are assigning a new value to the const variable "result". Therefore it throws an error
6. Similar to question 5, there is an error. Cannot reach line 13 as well if it errors out on line 7
